### ISSUE TITLE
The Tunnel Password is wrong. Could the author update the password?

### ISSUE THREAD

**Issue by wanglei666666666** [AutoSurveys/AutoSurvey#10]
I have tried the password in the closed issue, but the result is 404. Could you please provide me with the password? 
Thank you for considering my request!

**Comment by GuoQi2000** [comment]
Just visit https://autosurvey.serveo.net/
No password is required now.

**Comment by wanglei666666666** [comment]
I am sorry for asking such basic questions. I encountered an error while using the webpage you provided. Based on https://github.com/AutoSurveys/AutoSurvey/issues/5, I realized that I may need to provide options such as an API, but I am not quite sure how exactly to use that on the webpage.
![image](https://github.com/user-attachments/assets/ae4bec7a-279b-480c-8697-cdec735299d5)

**Comment by wanglei666666666** [comment]
Perhaps I have already solved the problem, but I am not sure if this is the optimal solution.

![image](https://github.com/user-attachments/assets/3a993204-ddfc-4e0a-8de3-471e604bdf5a)

**Comment by GuoQi2000** [comment]
The web demo is free and does not require users to provide API. We just found that our API quota was exhausted, but it has now been replenished and is working normally.

**Comment by wanglei666666666** [comment]
The issue has been resolved, and the automatically generated literature review is excellent. Thank you for your work and prompt responses.
