### ISSUE TITLE
Expanded output format options for web demo

### ISSUE THREAD

**Issue by shihongl1998** [AutoSurveys/AutoSurvey#2]
Hi, excellent work! I find this could be really helpful.

I tried the web demo and was wondering if more output format options could be provided. I understand that the web demo is primarily meant to showcase the paper's ideas, but it would be great if more useful formats like compiled LaTeX could be added, which would be really appreciated.

**Comment by qianlanwyd** [comment]
Thanks for your suggestions! But currently we are busy doing other projects, we will consider adding it in the future. Or you can change the prompt in the source file to let LLM output latex.
